[build]
  functions = "functions"

[[redirects]]
  from = "/api/trades"
  to = "/.netlify/functions/trades"
  status = 200

[[redirects]]
  from = "/api/refresh-trades"
  to = "/.netlify/functions/refresh-trades"
  status = 200

[[redirects]]
  from = "/api/price-history"
  to = "/.netlify/functions/price-history"
  status = 200

[[redirects]]
  from = "/api/protocol-yields"
  to = "/.netlify/functions/protocol-yields"
  status = 200

[[redirects]]
  from = "/api/tvl-history"
  to = "/.netlify/functions/tvl-history"
  status = 200
